"""add_price_parcel_to_trips

Revision ID: 1222e7c3f97e
Revises: 8fc87e77cd81
Create Date: 2026-07-29 23:19:41.556681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1222e7c3f97e'
down_revision: Union[str, Sequence[str], None] = '8fc87e77cd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('price_parcel', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'price_parcel')
    # ### end Alembic commands ###
