"""update_models_for_admin_panel

Revision ID: 22d0bc20f898
Revises: b9f48b5111d0
Create Date: 2026-06-21 12:12:35.102394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d0bc20f898'
down_revision: Union[str, Sequence[str], None] = 'b9f48b5111d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_templates', sa.Column('from_location_id', sa.Integer(), nullable=False))
    op.add_column('schedule_templates', sa.Column('to_location_id', sa.Integer(), nullable=False))
    op.add_column('schedule_templates', sa.Column('price_seated', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('schedule_templates', sa.Column('price_standing', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_index(op.f('ix_schedule_templates_day_type'), table_name='schedule_templates')
    op.create_foreign_key(None, 'schedule_templates', 'locations', ['to_location_id'], ['id'])
    op.create_foreign_key(None, 'schedule_templates', 'locations', ['from_location_id'], ['id'])
    op.drop_column('schedule_templates', 'route')
    op.add_column('trips', sa.Column('submitted_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trips', sa.Column('closed_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trips', 'users', ['closed_by_id'], ['id'])
    op.drop_column('trips', 'closed_by')
    op.drop_column('trips', 'cash_submitted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('cash_submitted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('closed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'closed_by_id')
    op.drop_column('trips', 'submitted_amount')
    op.add_column('schedule_templates', sa.Column('route', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'schedule_templates', type_='foreignkey')
    op.drop_constraint(None, 'schedule_templates', type_='foreignkey')
    op.create_index(op.f('ix_schedule_templates_day_type'), 'schedule_templates', ['day_type'], unique=False)
    op.drop_column('schedule_templates', 'price_standing')
    op.drop_column('schedule_templates', 'price_seated')
    op.drop_column('schedule_templates', 'to_location_id')
    op.drop_column('schedule_templates', 'from_location_id')
    # ### end Alembic commands ###
