"""add system_config table

Revision ID: 26b80719a04d
Revises: 9c18a0128d3e
Create Date: 2026-07-29 17:53:09.565718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b80719a04d'
down_revision: Union[str, Sequence[str], None] = '9c18a0128d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_seated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_standing', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_parcel', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('schedule_templates', 'price_seated',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('schedule_templates', 'price_standing',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_templates', 'price_standing',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('schedule_templates', 'price_seated',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_table('system_config')
    # ### end Alembic commands ###
