"""add_last_trip_date_to_user_stats

Revision ID: 2dffaf6abc17
Revises: 1222e7c3f97e
Create Date: 2026-07-30 18:59:38.094465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dffaf6abc17'
down_revision: Union[str, Sequence[str], None] = '1222e7c3f97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('last_trip_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'last_trip_date')
    # ### end Alembic commands ###
