"""add_close_comment_to_trips

Revision ID: 8fc87e77cd81
Revises: 8fe250fd65c2
Create Date: 2026-07-29 22:26:47.857062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc87e77cd81'
down_revision: Union[str, Sequence[str], None] = '8fe250fd65c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('close_comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'close_comment')
    # ### end Alembic commands ###
