"""add_submitted_cash_and_card_to_trips

Revision ID: 8fe250fd65c2
Revises: ad66b191a2fd
Create Date: 2026-07-29 21:59:50.234922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe250fd65c2'
down_revision: Union[str, Sequence[str], None] = 'ad66b191a2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('submitted_cash', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trips', sa.Column('submitted_card', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'submitted_card')
    op.drop_column('trips', 'submitted_cash')
    # ### end Alembic commands ###
