"""add_trip_conflict_unique_indexes

Revision ID: 9c18a0128d3e
Revises: 5c8a2c1fd9ab
Create Date: 2026-06-22 12:57:45.272904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c18a0128d3e'
down_revision: Union[str, Sequence[str], None] = '5c8a2c1fd9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_trip_driver_slot', 'trips', ['driver_id', 'departure_time'], unique=True, postgresql_where="status != 'CANCELLED'")
    op.create_index('uq_trip_vehicle_slot', 'trips', ['vehicle_id', 'departure_time'], unique=True, postgresql_where="status != 'CANCELLED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trip_vehicle_slot', table_name='trips', postgresql_where="status != 'CANCELLED'")
    op.drop_index('uq_trip_driver_slot', table_name='trips', postgresql_where="status != 'CANCELLED'")
    # ### end Alembic commands ###
