"""initial_schema

Revision ID: 9d96b3f09d68
Revises: 
Create Date: 2026-03-17 10:30:10.310442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d96b3f09d68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('PASSENGER', 'DRIVER', 'DISPATCHER', name='userrole'), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('total_standing', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'BOARDING', 'ACTIVE', 'COMPLETED', 'CLOSED', 'CANCELLED', name='tripstatus'), nullable=False),
    sa.Column('seats_limit_snapshot', sa.Integer(), nullable=False),
    sa.Column('standing_limit_snapshot', sa.Integer(), nullable=False),
    sa.Column('price_seated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_standing', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_departure_time'), 'trips', ['departure_time'], unique=False)
    op.create_index('ix_trips_search', 'trips', ['from_location_id', 'to_location_id', 'departure_time'], unique=False)
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('total_noshows', sa.Integer(), nullable=False),
    sa.Column('trust_score_cached', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_type', sa.Enum('SEATED', 'STANDING', 'PARCEL', name='bookingtype'), nullable=False),
    sa.Column('source', sa.Enum('BOT', 'WEB', 'PHONE', 'INSTAGRAM', 'DRIVER', name='bookingsource'), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'PAID', 'BOARDED', 'CANCELLED', 'NOSHOW', name='bookingstatus'), nullable=False),
    sa.Column('passengers_count', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_passenger_id'), 'bookings', ['passenger_id'], unique=False)
    op.create_index('ix_bookings_trip_status', 'bookings', ['trip_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_trip_status', table_name='bookings')
    op.drop_index(op.f('ix_bookings_passenger_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('user_stats')
    op.drop_index('ix_trips_search', table_name='trips')
    op.drop_index(op.f('ix_trips_departure_time'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
