"""drop price columns from schedule_templates

Revision ID: ad66b191a2fd
Revises: 26b80719a04d
Create Date: 2026-07-29 18:25:28.216517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad66b191a2fd'
down_revision: Union[str, Sequence[str], None] = '26b80719a04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_templates', 'price_standing')
    op.drop_column('schedule_templates', 'price_seated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_templates', sa.Column('price_seated', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('schedule_templates', sa.Column('price_standing', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
