"""add_is_active_to_users

Revision ID: d033cbb3c465
Revises: db0be8345da8
Create Date: 2026-08-30 16:36:33.513654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd033cbb3c465'
down_revision: Union[str, Sequence[str], None] = 'db0be8345da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'ADMIN';")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'admin';")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT 'true' NOT NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
